encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("edit/<str:title>/", views.edit, name="edit"),
    path("random/", views.random_page, name="random_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("encyclopedia.urls"))]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, reverse

from . import util

from .forms import NewEntryForm

import random


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request, title):
    entry = util.get_entry(title)
    if entry:
        return render(
            request,
            "encyclopedia/entry.html",
            {"title": title, "entry": util.html_to_markdown(entry)},
        )

    else:
        return render(
            request,
            "encyclopedia/error.html",
            {"message": f'"{title}" Not Found In Wiki Entries'},
        )


def search(request):
    if request.method == "GET":
        query = request.GET.get("query")
        entries = util.list_entries()
        matches = [entry for entry in entries if query.lower() in entry.lower()]
        exact_match = [entry for entry in entries if query.lower() == entry.lower()]

        if exact_match:
            return HttpResponseRedirect(reverse("entry", kwargs={"title": exact_match}))

        elif matches:
            return render(
                request,
                "encyclopedia/search.html",
                {"matches": matches, "query": query},
            )
        else:
            return render(
                request,
                "encyclopedia/error.html",
                {"message": f'"{query}" Not Found in Wiki Entries'},
            )
    else:
        return redirect(reverse("index"))


def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title):
                return render(
                    request,
                    "encyclopedia/error.html",
                    {"message": "Entry Already Exists in Wiki", "title": title},
                )
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(
                    reverse("encyclopedia:entry", kwargs={"title": title})
                )
        else:
            return render(request, "encyclopedia/new.html", {"form": form})
    else:
        form = NewEntryForm()
        return render(request, "encyclopedia/new.html", {"form": form})


def edit(request, title):
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        if form.is_valid():
            new_content = form.cleaned_data["content"]
            print(new_content)
            util.save_entry(title, new_content)
            return HttpResponseRedirect(
                reverse("encyclopedia:entry", kwargs={"title": title})
            )
        else:
            return render(
                request, "encyclopedia/edit.html", {"form": form, "title": title}
            )

    else:
        form = NewEntryForm(initial={"title": title, "content": util.get_entry(title)})
        form.fields["title"].widget.attrs["readonly"] = True
        return render(request, "encyclopedia/edit.html", {"form": form, "title": title})


def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return redirect(reverse("encyclopedia:entry", kwargs={"title": random_entry}))

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <div>
                    <form action="{% url 'encyclopedia:search' %}" method="GET">
                        {% csrf_token %}
                        <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
                    </form>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>